name: fitness
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ## MOBX
  mobx: ^2.3.0+1
  mobx_codegen: ^2.6.0+1
  flutter_mobx: ^2.2.0+2
  build_runner: ^2.4.8
  http: ^1.2.0
  hive: ^2.2.3
  get: ^4.6.6
  path_provider: ^2.1.2
  get_storage: ^2.1.1
  jwt_decoder: ^2.0.1
  uuid: ^4.3.3
  reorderable_grid_view: ^2.2.8
  flutter_gen: ^5.4.0
  dio: ^5.4.3+1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/exercises/
    - assets/res/
